# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='member_name',
        ),
        migrations.AddField(
            model_name='family',
            name='member_first_name',
            field=models.CharField(default='sistla', max_length=20),
        ),
        migrations.AddField(
            model_name='family',
            name='member_last_name',
            field=models.CharField(default='test', max_length=20),
        ),
    ]
