# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_expenses', '0002_auto_20161228_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='member_first_name',
            field=models.CharField(default='sistla', max_length=200),
        ),
        migrations.AlterField(
            model_name='family',
            name='member_last_name',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
