# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_expenses', '0003_auto_20161228_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True))
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monthly_expenses.Root'),
            preserve_default=False,
        ),
    ]
