# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_expenses', '0004_auto_20161228_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monthly_expenses.Root'),
        ),
    ]
