# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_expenses', '0006_family_login_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='login_name',
            field=models.CharField(default='klhgbyuard', max_length=150, unique=True),
        ),
    ]
